'use client';
import {useState} from 'react';
import Image from 'next/image';

const specialties=[
 ['Endocrinologia','Metabolismo, hormônios e saúde integral.'],['Pediatria','Cuidado atento em cada fase da infância.'],['Dermatologia','Saúde da pele, cabelos e unhas.'],['Ginecologia','Acompanhamento da saúde feminina.'],['Psiquiatria','Escuta qualificada e saúde emocional.'],['Neurologia infantil','Desenvolvimento e potencial de cada criança.'],['Nutrição','Hábitos que sustentam qualidade de vida.'],['Odontologia','Prevenção, estética e reabilitação oral.'],['Estética & tricologia','Ciência e cuidado de dentro para fora.']
];
const doctors=[['Dra. Tassyllane','Dermatologia','5594981115425'],['Dr. Deivy Siqueira','Endocrinologia','5594984271991'],['Dra. Íris','Pediatria','5594992692830'],['Dra. Bianka','Ginecologia',''],['Dra. Nathalia','Psiquiatria',''],['Dra. Suellen Fontinele','Neurologia infantil','']];
export default function Home(){const[menu,setMenu]=useState(false);return <main>
 <header><a className="logo" href="#inicio"><Image src="/logo.jpg" alt="Clínica Vivace Parauapebas" width={100} height={100} priority/><span>CLÍNICA<strong>VIVACE</strong><small>PARAUAPEBAS</small></span></a><nav className={menu?'show':''}><a href="#vivace" onClick={()=>setMenu(false)}>A Vivace</a><a href="#especialidades" onClick={()=>setMenu(false)}>Especialidades</a><a href="#equipe" onClick={()=>setMenu(false)}>Equipe</a><a href="#contato" onClick={()=>setMenu(false)}>Contato</a></nav><a className="schedule" href="https://wa.me/5594981115425" target="_blank">Agendar consulta <i>↗</i></a><button onClick={()=>setMenu(!menu)}>{menu?'FECHAR':'MENU'}</button></header>
 <section className="hero" id="inicio"><div className="heroText"><p className="label">CENTRO MÉDICO MULTIDISCIPLINAR</p><h1>Saúde que<br/><em>conecta</em> você<br/>à vida.</h1><div className="heroIntro"><span>01 — VIVACE</span><p>Especialidades, exames e cuidado integrado em um só lugar. Para cada fase, uma escuta. Para cada necessidade, um caminho.</p></div></div><div className="heroMedia"><div className="vShape">V</div><div className="heroPhoto"/><div className="availability"><i/> Atendimento em Parauapebas</div></div><a className="scroll" href="#vivace">DESCUBRA A VIVACE ↓</a></section>
 <section className="intro" id="vivace"><p className="vertical">MEDICINA INTEGRADA</p><div><p className="label">UM NOVO JEITO DE CUIDAR</p><h2>Viver bem começa quando<br/>o cuidado olha para o <em>todo.</em></h2></div><div className="introCopy"><p>A Vivace reúne diferentes especialidades em uma estrutura preparada para consultas, exames complementares e procedimentos ambulatoriais.</p><a href="#especialidades">Conheça nossas áreas <span>→</span></a></div></section>
 <section className="constellation" id="especialidades"><div className="constHead"><p className="label">CUIDADO CONECTADO</p><h2>Muitas especialidades.<br/><em>Uma só Vivace.</em></h2><p>Cada ponto é uma área de cuidado. Juntas, elas formam uma visão mais completa da sua saúde.</p></div><div className="orbit"><div className="core"><b>V</b><span>VIVACE</span></div>{specialties.map((s,i)=><article style={{'--i':i} as React.CSSProperties} key={s[0]}><i>{String(i+1).padStart(2,'0')}</i><h3>{s[0]}</h3><p>{s[1]}</p></article>)}</div><div className="specialtyList">{specialties.map((s,i)=><article key={s[0]}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{s[0]}</h3><p>{s[1]}</p></div></article>)}</div></section>
 <section className="path"><div className="pathImage"/><div className="pathCopy"><p className="label">SUA JORNADA NA VIVACE</p><h2>Do primeiro contato<br/>ao cuidado <em>contínuo.</em></h2><ol><li><span>01</span><div><b>Escuta</b><p>Entendemos sua necessidade e direcionamos o melhor atendimento.</p></div></li><li><span>02</span><div><b>Avaliação</b><p>Consulta especializada com olhar cuidadoso para o seu contexto.</p></div></li><li><span>03</span><div><b>Integração</b><p>Quando necessário, especialidades e exames se conectam.</p></div></li><li><span>04</span><div><b>Acompanhamento</b><p>Orientação clara para continuar cuidando da sua saúde.</p></div></li></ol></div></section>
 <section className="evidence"><div><b>10+</b><p>frentes de cuidado<br/>em um só endereço</p></div><div><b>08—20h</b><p>atendimento de segunda<br/>a sexta-feira</p></div><blockquote>“Cuidar é entender que cada pessoa é um universo inteiro.”</blockquote></section>
 <section className="team" id="equipe"><div className="teamTitle"><p className="label">QUEM CUIDA DE VOCÊ</p><h2>Conhecimento<br/>que se encontra.</h2></div><div className="teamPhoto"><span>EQUIPE MULTIDISCIPLINAR</span></div><div className="doctorList">{doctors.map((d,i)=><div key={d[0]}><span>{String(i+1).padStart(2,'0')}</span><b>{d[0]}</b><div className="docMeta"><small>{d[1]}</small>{d[2] && <a href={`https://wa.me/${d[2]}`} target="_blank">WhatsApp ↗</a>}</div></div>)}<p>Consulte a agenda e a disponibilidade de cada profissional diretamente com a clínica.</p></div></section>
 <section className="structure"><div className="structureWords"><span>ACOLHIMENTO</span><span>CIÊNCIA</span><span>SEGURANÇA</span></div><div className="structureCopy"><p className="label">ESTRUTURA VIVACE</p><h2>Um espaço pensado<br/>para fazer você se<br/><em>sentir cuidado.</em></h2><p>Ambientes contemporâneos, atendimento organizado e uma localização acessível no Parque dos Carajás.</p></div><div className="structureImage"/></section>
 <section className="contact" id="contato"><div className="contactTop"><p>PRONTO PARA CUIDAR DE VOCÊ</p><h2>Vamos marcar<br/>seu <em>momento?</em></h2><a href="https://wa.me/5594981115425" target="_blank">AGENDAR PELO WHATSAPP <span>↗</span></a></div><div className="contactInfo"><div><small>ENDEREÇO</small><p>Av. Potiguá, Quadra 106, Lote 10<br/>Parque dos Carajás<br/>Parauapebas — PA</p></div><div><small>HORÁRIOS</small><p>Segunda a sexta · 08h às 20h<br/>Sábado · 08h às 12h</p></div><div><small>CONTATO</small><a href="tel:+5594981115425">(94) 98111-5425</a><a href="https://www.instagram.com/clinicavivace_parauapebas/" target="_blank">Instagram</a><a href="https://www.facebook.com/pages/Cl%C3%ADnica%20Vivace%20Parauapebas/440915009114487/" target="_blank">Facebook</a></div></div></section>
 <footer><a className="logo inverse" href="#inicio"><Image src="/logo.jpg" alt="Clínica Vivace Parauapebas" width={100} height={100}/><span>CLÍNICA<strong>VIVACE</strong><small>PARAUAPEBAS</small></span></a><p>© 2026 · Clínica Vivace Parauapebas</p><a href="#inicio">VOLTAR AO TOPO ↑</a></footer><a className="wa" href="https://wa.me/5594981115425" target="_blank" aria-label="WhatsApp">WA</a>
 </main>}
